trigger:
  branches:
    include:
      - HTTP_branch

stages:
- stage: Install
  displayName: 'Install Dependencies'
  jobs:
  - job: InstallJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.x'
          addToPath: true

      - script: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-cov
        displayName: 'Install dependencies'

- stage: Test
  displayName: 'Run Tests'
  dependsOn: Install
  jobs:
  - job: TestJob
    pool:
      name: Default
    steps:
      - script: |
          python -m pytest --maxfail=5 --disable-warnings --cov=. --cov-report=xml --cov-report=html || echo "Pytest failed"
        displayName: 'Run Pytest and generate coverage report'
        env:
          PYTHONHTTPSVERIFY: '0'

      - script: |
          python -m pip show pytest  # Check if pytest is installed
        displayName: 'Check Pytest Installation'

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '**/TEST-*.xml'
          failOnEmptyTestResults: true

      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: 'cobertura'  # Use the cobertura format for coverage reports
          codeCoverageReportPath: 'coverage.xml'  # Path to the coverage report
