trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  keyVaultName: 'your-key-vault-name'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - task: AzureKeyVault@2
  inputs:
    azureSubscription: 'your-service-connection-name'
    keyVaultName: 'your-key-vault-name'
    secretsFilter: 'db-*'
    runAsPreJob: true

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install pytest-cov
    displayName: 'Install dependencies'

  - script: |
      pytest --maxfail=5 --disable-warnings --cov=. --cov-report=xml --cov-report=html
    displayName: 'Run Pytest and generate coverage report'
    env:
      PYTHONHTTPSVERIFY: '0'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/TEST-*.xml'
      failOnEmptyTestResults: true

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'cobertura'  # Use the cobertura format for coverage reports
      codeCoverageReportPath: 'coverage.xml'  # Path to the coverage report

# Store the following secrets in Azure Key Vault:

# db-server: The SQL Server name or IP.
# db-database: The database name.
# db-username: The username for authentication.
# db-password: The password for authentication.
# db-authentication: (Optional) Type of authentication (e.g., ActiveDirectoryPassword).
